### ISSUE TITLE
是否可以提供一种docker的部署方式

### ISSUE THREAD

**Issue by schizobulia** [herghost000/egg-ffmpeg#1]
看到使用了mysql redis ffmpeg，使用docker会方便很多。
是否需要帮忙，最近在看视频处理之类的项目。

**Comment by mykioer** [comment]
同问

**Comment by schizobulia** [comment]
后续看了相关代码 该项目是使用了一个fluent-ffmpeg的库，依然需要去编译ffmpeg

不过我们可以找一个ffmpeg的docker镜像即可  然后把node环境搞进去就可以 @mykioer
